// localStorage.clear() ;

const employees = [
  {
    id: 1,
    email: "rahul@example.com",
    password: "123",
    name:'Rahul' ,
     taskCount: {
      active: 2,
      newTask: 5,
      completed: 3,
      failed: 7,
    },
    tasks: [
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Design Login Page",
        taskDescription: "Create a responsive login page using React and Tailwind CSS.",
        taskDate: "2026-07-06",
        category: "Design",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Fix Navbar",
        taskDescription: "Resolve alignment issues in the navigation bar.",
        taskDate: "2026-07-03",
        category: "Frontend",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "API Integration",
        taskDescription: "Connect login page with authentication API.",
        taskDate: "2026-07-01",
        category: "Backend",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: true,
        taskTitle: "Employee Dashboard",
        taskDescription: "Develop the employee dashboard UI",
        taskDate: "2026-07-01",
        category: "Backend",
      },
    ],
  },
  {
    id: 2,
    email: "priya@example.com",
    password: "123",
    name:'Priya' ,
     taskCount: {
      active: 10,
      newTask: 12,
      completed: 17,
      failed: 3,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Employee Dashboard",
        taskDescription: "Develop the employee dashboard UI.",
        taskDate: "2026-07-07",
        category: "Frontend",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Profile Page",
        taskDescription: "Create employee profile page.",
        taskDate: "2026-07-02",
        category: "Frontend",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Task Card Component",
        taskDescription: "Create reusable task card component.",
        taskDate: "2026-07-08",
        category: "React",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Bug Fixing",
        taskDescription: "Fix task rendering bug.",
        taskDate: "2026-06-30",
        category: "Debugging",
      },
    ],
  },
  {
    id: 3,
    email: "aman@example.com",
    password: "123",
    name:'Aman' ,
    taskCount: {
      active: 11,
      newTask: 9,
      completed: 6,
      failed: 5,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Database Schema",
        taskDescription: "Design MongoDB collections.",
        taskDate: "2026-07-06",
        category: "Database",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "JWT Authentication",
        taskDescription: "Implement JWT login authentication.",
        taskDate: "2026-07-02",
        category: "Backend",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "REST API",
        taskDescription: "Create task CRUD APIs.",
        taskDate: "2026-07-09",
        category: "Backend",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Deploy Server",
        taskDescription: "Deploy backend on Render.",
        taskDate: "2026-06-28",
        category: "Deployment",
      },
    ],
  },
  {
    id: 4,
    email: "neha@example.com",
    password: "123",
    name:'Neha' ,
    taskCount: {
      active: 5,
      newTask: 7,
      completed: 2,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Create Reports",
        taskDescription: "Generate weekly employee reports.",
        taskDate: "2026-07-06",
        category: "Management",
      },
      {
        active: false,
        newTask: false,
        completed:true,
        failed:false,
        taskTitle:"Attendance Module",
        taskDescription:"Complete attendance management module.",
        taskDate:"2026-07-01",
        category:"React",
      },
      {
        active:true,
        newTask:false,
        completed:false,
        failed:false,
        taskTitle:"Optimize Components",
        taskDescription:"Improve rendering performance.",
        taskDate:"2026-07-10",
        category:"Optimization",
      },
    ],
  },
  {
    id: 5,
    email: "rohit@example.com",
    password: "123",
    name:'Rohit' ,
    taskCount: {
      active: 6,
      newTask: 5,
      completed: 4,
      failed: 3,
    },
    tasks: [
      {
        active:true,
        newTask:true,
        completed:false,
        failed:false,
        taskTitle:"Testing",
        taskDescription:"Perform unit testing for task module.",
        taskDate:"2026-07-07",
        category:"Testing",
      },
      {
        active:false,
        newTask:false,
        completed:true,
        failed:false,
        taskTitle:"Landing Page",
        taskDescription:"Design company landing page.",
        taskDate:"2026-07-02",
        category:"UI/UX",
      },
      {
        active:true,
        newTask:false,
        completed:false,
        failed:false,
        taskTitle:"Dark Mode",
        taskDescription:"Add dark mode support.",
        taskDate:"2026-07-09",
        category:"Frontend",
      },
      {
        active:false,
        newTask:false,
        completed:false,
        failed:true,
        taskTitle:"Notification System",
        taskDescription:"Implement push notifications.",
        taskDate:"2026-06-29",
        category:"Backend",
      },
      {
        active:true,
        newTask:true,
        completed:false,
        failed:false,
        taskTitle:"Documentation",
        taskDescription:"Write project documentation.",
        taskDate:"2026-07-11",
        category:"Documentation",
      },
    ],
  },
];

const admin = [
  {
    id: 1,
    name:'Lalit Baghel' ,
    email: "lalitbaghel0708@gmail.com",
    password: "123",
  },
];

export const setLocalStorage = ()=> {
    localStorage.setItem('employees',JSON.stringify(employees)) ; 
    localStorage.setItem('admin',JSON.stringify(admin)) ; 
}
export function getLocalStorage(){
    const employees = JSON.parse(localStorage.getItem('employees') ) ;
    const admin = JSON.parse(localStorage.getItem('admin') ) ;
    return {employees , admin} ;
}